/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secure.sms;

import all_requests.Request;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import all_requests.RequestDAO;
import all_requests.RequestDAOImpl;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import supplies.Supply;
import supplies.SupplyDAOImpl;
/**
 *
 * @author Lenovo
 */
public class AdminGUI extends javax.swing.JFrame {
    RequestDAOImpl requestDAOImpl = new RequestDAOImpl();
    private SupplyDAOImpl supplyDAOImpl = new SupplyDAOImpl();
    private Supply supply = null;

    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() {
        initComponents();
        refreshTBL();
        loadFilteredRequests();
        loadRequestsByStatus(requestsTBL, "Pending");
        loadRequestsByStatus(inProgressTBL, "In Progress");
        loadRequestsByStatus(recordTBL, "Completed");
    
    }
    public void login_admin(){
        AdminLoginGUI adminloginGUI = new AdminLoginGUI(this, true);
        
        adminloginGUI.show(true);
        
    }

    private void loadFilteredRequests() {
        String selectedType = typeCB.getSelectedItem().toString();
        String selectedPriority = priorityCB.getSelectedItem().toString();
        
        DefaultTableModel model = (DefaultTableModel) requestsTBL.getModel();
        model.setRowCount(0); 
        ArrayList<Request> requests = requestDAOImpl.readFiltered(selectedType,selectedPriority);

        for (Request request : requests) {
            model.addRow(new Object[] {
                request.getRequest_id(),
                request.getUser_id(),
                request.getRequested_by(),
                request.getRequest_type(),
                request.getRequest_info(),
                request.getPriority(),
                request.getDate_created()
            });
        }
    }

    
    public void refreshTBL() {
        ArrayList<Request> requests = requestDAOImpl.read_all(); // use your actual DAO instance here
        DefaultTableModel model = (DefaultTableModel) requestsTBL.getModel();
        model.setRowCount(0); // Clear table before repopulating

        for (Request request : requests) {
            model.addRow(new Object[]{
                request.getRequest_id(),
                request.getUser_id(),
                request.getRequested_by(),
                request.getRequest_info(),
                request.getRequest_type(),
                request.getPriority(),
                request.getDate_created()
            });

        }
    }
    public void loadRequestsByStatus(JTable table, String status) {
        RequestDAOImpl requestDAOImpl = new RequestDAOImpl();
        ArrayList<Request> requests = requestDAOImpl.readByStatus(status);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0); 

        for (Request request : requests) {
            model.addRow(new Object[]{
                request.getRequest_id(),
                request.getUser_id(),
                request.getRequested_by(),
                request.getRequest_info(),
                request.getRequest_type(),
                request.getPriority(),
                request.getDate_created()
            });
        }
    }
    public void reloadTabs() {
    loadRequestsByStatus(requestsTBL, "Pending");
    loadRequestsByStatus(inProgressTBL, "In Progress");
    loadRequestsByStatus(recordTBL, "Completed");
}

    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consumablePUM = new javax.swing.JPopupMenu();
        consumableUpdate = new javax.swing.JMenuItem();
        consumableDelete = new javax.swing.JMenuItem();
        equipmentPUM = new javax.swing.JPopupMenu();
        equipmentUpdate = new javax.swing.JMenuItem();
        equipmentDelete = new javax.swing.JMenuItem();
        technologyPUM = new javax.swing.JPopupMenu();
        technologyUpdate = new javax.swing.JMenuItem();
        technologyDelete = new javax.swing.JMenuItem();
        othersPUM = new javax.swing.JPopupMenu();
        othersUpdate = new javax.swing.JMenuItem();
        othersDelete = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestsTBL = new javax.swing.JTable();
        searchTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox<>();
        priorityCB = new javax.swing.JComboBox<>();
        searchBTN = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        inProgressTBL = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        recordTBL = new javax.swing.JTable();
        statusCB = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consumableTBL = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        consumableNameTF = new javax.swing.JTextField();
        consumablePreferencesTF = new javax.swing.JTextField();
        consumableQuantityTF = new javax.swing.JTextField();
        consumableSaveBTN = new javax.swing.JButton();
        consumableCancelTF = new javax.swing.JButton();
        consumableSearchBTN = new javax.swing.JButton();
        consumableSearchTF = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        equipmentTBL = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        equipmentQuantityTF = new javax.swing.JTextField();
        equipmentNameTF = new javax.swing.JTextField();
        equipmentSaveBTN = new javax.swing.JButton();
        equipmentCancelBTN = new javax.swing.JButton();
        equipmentPreferencesTF = new javax.swing.JTextField();
        equipmentSearchBTN = new javax.swing.JButton();
        equipmentSearchTF = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        technologySearchTF = new javax.swing.JTextField();
        technologySearchBTN = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        technologyTBL = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        technologyNameTF = new javax.swing.JTextField();
        technologyQuantityTF = new javax.swing.JTextField();
        technologySaveBTN = new javax.swing.JButton();
        technologyCancelBTN = new javax.swing.JButton();
        technologyPreferencesTF = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        othersTBL = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        othersNameTF = new javax.swing.JTextField();
        othersQuantityTF = new javax.swing.JTextField();
        othersPreferencesTF = new javax.swing.JTextField();
        othersSaveBTN = new javax.swing.JButton();
        othersCancelBTN = new javax.swing.JButton();
        othersSearchTF = new javax.swing.JTextField();
        othersSearchBTN = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        userMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        consumableUpdate.setText("jMenuItem1");
        consumableUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableUpdateActionPerformed(evt);
            }
        });
        consumablePUM.add(consumableUpdate);

        consumableDelete.setText("jMenuItem2");
        consumableDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableDeleteActionPerformed(evt);
            }
        });
        consumablePUM.add(consumableDelete);

        equipmentUpdate.setText("jMenuItem1");
        equipmentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentUpdateActionPerformed(evt);
            }
        });
        equipmentPUM.add(equipmentUpdate);

        equipmentDelete.setText("jMenuItem1");
        equipmentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentDeleteActionPerformed(evt);
            }
        });
        equipmentPUM.add(equipmentDelete);

        technologyUpdate.setText("jMenuItem1");
        technologyUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technologyUpdateActionPerformed(evt);
            }
        });
        technologyPUM.add(technologyUpdate);

        technologyDelete.setText("jMenuItem1");
        technologyDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technologyDeleteActionPerformed(evt);
            }
        });
        technologyPUM.add(technologyDelete);

        othersUpdate.setText("jMenuItem1");
        othersUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersUpdateActionPerformed(evt);
            }
        });
        othersPUM.add(othersUpdate);

        othersDelete.setText("jMenuItem1");
        othersDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersDeleteActionPerformed(evt);
            }
        });
        othersPUM.add(othersDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jButton1.setText("PENDING");

        jButton4.setText("IN PROGRESS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton5.setText("COMPLETED");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(704, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(494, 299));

        requestsTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                " Request ID", "User ID", "Requested by", "Request Info", "Type", "Priority ", "Created"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestsTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestsTBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(requestsTBL);
        if (requestsTBL.getColumnModel().getColumnCount() > 0) {
            requestsTBL.getColumnModel().getColumn(0).setResizable(false);
            requestsTBL.getColumnModel().getColumn(1).setResizable(false);
            requestsTBL.getColumnModel().getColumn(2).setResizable(false);
            requestsTBL.getColumnModel().getColumn(3).setResizable(false);
            requestsTBL.getColumnModel().getColumn(4).setResizable(false);
            requestsTBL.getColumnModel().getColumn(5).setResizable(false);
            requestsTBL.getColumnModel().getColumn(6).setResizable(false);
        }

        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Search:");

        jLabel2.setText("Filter:");

        typeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Service", "Supply" }));
        typeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeCBActionPerformed(evt);
            }
        });

        priorityCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Low", "Medium", "High", "Urgent" }));
        priorityCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityCBActionPerformed(evt);
            }
        });

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        jLabel23.setText("Type:");

        jLabel24.setText("Priority:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBTN)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priorityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBTN)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Request List", jPanel2);

        inProgressTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                " Request ID", "User ID", "Requested by", "Request Info", "Type", "Priority ", "Created"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inProgressTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inProgressTBLMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(inProgressTBL);
        if (inProgressTBL.getColumnModel().getColumnCount() > 0) {
            inProgressTBL.getColumnModel().getColumn(0).setResizable(false);
            inProgressTBL.getColumnModel().getColumn(1).setResizable(false);
            inProgressTBL.getColumnModel().getColumn(2).setResizable(false);
            inProgressTBL.getColumnModel().getColumn(3).setResizable(false);
            inProgressTBL.getColumnModel().getColumn(4).setResizable(false);
            inProgressTBL.getColumnModel().getColumn(5).setResizable(false);
            inProgressTBL.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("In Progress", jPanel10);

        recordTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                " Request ID", "User ID", "Requested by", "Request Info", "Type", "Priority ", "Created"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recordTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordTBLMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(recordTBL);
        if (recordTBL.getColumnModel().getColumnCount() > 0) {
            recordTBL.getColumnModel().getColumn(0).setResizable(false);
            recordTBL.getColumnModel().getColumn(1).setResizable(false);
            recordTBL.getColumnModel().getColumn(2).setResizable(false);
            recordTBL.getColumnModel().getColumn(3).setResizable(false);
            recordTBL.getColumnModel().getColumn(4).setResizable(false);
            recordTBL.getColumnModel().getColumn(5).setResizable(false);
            recordTBL.getColumnModel().getColumn(6).setResizable(false);
        }

        statusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completed", "Rejected" }));
        statusCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(830, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Record", jPanel4);

        consumableTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supply ID", "Supply Name", "Quantity", "Preferences"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        consumableTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                consumableTBLMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(consumableTBL);

        jLabel5.setText("Search supply:");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Supplies Entry/Update Form"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Fill out the fields below...");

        jLabel4.setText("Supply Name:");

        jLabel6.setText("Quantity:");

        jLabel7.setText("Preferences");

        consumableQuantityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableQuantityTFActionPerformed(evt);
            }
        });

        consumableSaveBTN.setText("Save");
        consumableSaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableSaveBTNActionPerformed(evt);
            }
        });

        consumableCancelTF.setText("Cancel");
        consumableCancelTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableCancelTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(consumableSaveBTN)
                                .addGap(18, 18, 18)
                                .addComponent(consumableCancelTF)
                                .addGap(0, 31, Short.MAX_VALUE))
                            .addComponent(consumableQuantityTF)
                            .addComponent(consumablePreferencesTF)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumableNameTF)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(consumableNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(consumableQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(consumablePreferencesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consumableSaveBTN)
                    .addComponent(consumableCancelTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consumableSearchBTN.setText("Search");
        consumableSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableSearchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consumableSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consumableSearchBTN))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(consumableSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consumableSearchBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Consumable", jPanel5);

        equipmentTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supply ID", "Supply Name", "Quantity", "Preferences"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipmentTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                equipmentTBLMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(equipmentTBL);

        jLabel8.setText("Search supply:");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Supplies Entry/Update Form"));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("Fill out the fields below...");

        jLabel10.setText("Supply Name:");

        jLabel11.setText("Quantity:");

        jLabel12.setText("Preferences");

        equipmentSaveBTN.setText("Save");
        equipmentSaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentSaveBTNActionPerformed(evt);
            }
        });

        equipmentCancelBTN.setText("Cancel");
        equipmentCancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentCancelBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(equipmentSaveBTN)
                                        .addGap(18, 18, 18)
                                        .addComponent(equipmentCancelBTN))
                                    .addComponent(equipmentPreferencesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(equipmentQuantityTF, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(equipmentNameTF)))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(equipmentNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(equipmentQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(equipmentPreferencesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipmentSaveBTN)
                    .addComponent(equipmentCancelBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        equipmentSearchBTN.setText("Search");
        equipmentSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentSearchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(equipmentSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(equipmentSearchBTN)
                    .addGap(85, 85, 85)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(equipmentSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipmentSearchBTN)))
                    .addContainerGap(211, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Classroom Equipment", jPanel6);

        technologySearchBTN.setText("Search");
        technologySearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technologySearchBTNActionPerformed(evt);
            }
        });

        technologyTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supply ID", "Supply Name", "Quantity", "Preferences"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        technologyTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                technologyTBLMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(technologyTBL);

        jLabel13.setText("Search supply:");

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Supplies Entry/Update Form"));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setText("Fill out the fields below...");

        jLabel15.setText("Supply Name:");

        jLabel16.setText("Quantity:");

        jLabel17.setText("Preferences");

        technologySaveBTN.setText("Save");
        technologySaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technologySaveBTNActionPerformed(evt);
            }
        });

        technologyCancelBTN.setText("Cancel");
        technologyCancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technologyCancelBTNActionPerformed(evt);
            }
        });

        technologyPreferencesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technologyPreferencesTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(31, 31, 31)
                        .addComponent(technologyQuantityTF))
                    .addComponent(jLabel14)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(technologyNameTF))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(technologySaveBTN)
                                .addGap(18, 18, 18)
                                .addComponent(technologyCancelBTN))
                            .addComponent(technologyPreferencesTF, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(technologyNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(technologyQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(technologyPreferencesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(technologyCancelBTN)
                    .addComponent(technologySaveBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(technologySearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(technologySearchBTN)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(technologySearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(technologySearchBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
        );

        jTabbedPane2.addTab("Technology", jPanel7);

        othersTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supply ID", "Supply Name", "Quantity", "Preferences"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        othersTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                othersTBLMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(othersTBL);

        jLabel18.setText("Search supply:");

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Supplies Entry/Update Form"));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setText("Fill out the fields below...");

        jLabel20.setText("Supply Name:");

        jLabel21.setText("Quantity:");

        jLabel22.setText("Preferences");

        othersSaveBTN.setText("Save");
        othersSaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersSaveBTNActionPerformed(evt);
            }
        });

        othersCancelBTN.setText("Cancel");
        othersCancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersCancelBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(othersQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(othersNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(othersSaveBTN)
                                .addGap(18, 18, 18)
                                .addComponent(othersCancelBTN))
                            .addComponent(othersPreferencesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(othersNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(othersQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(othersPreferencesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(othersSaveBTN)
                    .addComponent(othersCancelBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        othersSearchBTN.setText("Search");
        othersSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersSearchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(othersSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othersSearchBTN))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(othersSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othersSearchBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Others", jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Supply List", jPanel3);

        jMenu1.setText("File");

        userMI.setText("User");
        userMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMIActionPerformed(evt);
            }
        });
        jMenu1.add(userMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void requestsTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsTBLMouseClicked
       
    if (evt.getClickCount() == 2 && !evt.isConsumed()) {
        evt.consume(); // prevent further handling
        int row = requestsTBL.getSelectedRow();

        if (row >= 0) {
            Object idValue = requestsTBL.getValueAt(row, 0);
            if (idValue != null) {
                int requestId = (int) idValue;
                Request selectedRequest = requestDAOImpl.read_one(requestId);
                if (selectedRequest != null) {
                    RequestDetailsGUI dialog = new RequestDetailsGUI(this, selectedRequest);
                    dialog.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Request ID selected.");
            }
        }
    }


    }//GEN-LAST:event_requestsTBLMouseClicked

    private void userMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMIActionPerformed
        CreateUserGUI dialog = new CreateUserGUI(this, true);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_userMIActionPerformed

    private void consumableTBLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consumableTBLMouseReleased
       
    }//GEN-LAST:event_consumableTBLMouseReleased

    private void consumableQuantityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableQuantityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumableQuantityTFActionPerformed

    private void consumableSaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableSaveBTNActionPerformed
    
    }//GEN-LAST:event_consumableSaveBTNActionPerformed

    private void consumableCancelTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableCancelTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_consumableCancelTFActionPerformed

    private void consumableSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableSearchBTNActionPerformed
       
    }//GEN-LAST:event_consumableSearchBTNActionPerformed

    private void equipmentTBLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentTBLMouseReleased
       
    }//GEN-LAST:event_equipmentTBLMouseReleased

    private void equipmentSaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentSaveBTNActionPerformed
    
    }//GEN-LAST:event_equipmentSaveBTNActionPerformed

    private void equipmentCancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentCancelBTNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_equipmentCancelBTNActionPerformed

    private void equipmentSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentSearchBTNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_equipmentSearchBTNActionPerformed

    private void technologySearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technologySearchBTNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_technologySearchBTNActionPerformed

    private void technologyTBLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_technologyTBLMouseReleased
        
    }//GEN-LAST:event_technologyTBLMouseReleased

    private void technologySaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technologySaveBTNActionPerformed
    
    }//GEN-LAST:event_technologySaveBTNActionPerformed

    private void technologyCancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technologyCancelBTNActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_technologyCancelBTNActionPerformed

    private void technologyPreferencesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technologyPreferencesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_technologyPreferencesTFActionPerformed

    private void othersTBLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othersTBLMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_othersTBLMouseReleased

    private void othersSaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersSaveBTNActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_othersSaveBTNActionPerformed

    private void othersCancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersCancelBTNActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_othersCancelBTNActionPerformed

    private void othersSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersSearchBTNActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_othersSearchBTNActionPerformed

    private void consumableUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableUpdateActionPerformed
       
    }//GEN-LAST:event_consumableUpdateActionPerformed

    private void consumableDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableDeleteActionPerformed
       
    }//GEN-LAST:event_consumableDeleteActionPerformed

    private void equipmentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentUpdateActionPerformed
        
    }//GEN-LAST:event_equipmentUpdateActionPerformed

    private void equipmentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentDeleteActionPerformed
       
    }//GEN-LAST:event_equipmentDeleteActionPerformed

    private void technologyUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technologyUpdateActionPerformed
      
    }//GEN-LAST:event_technologyUpdateActionPerformed

    private void technologyDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technologyDeleteActionPerformed
      
    }//GEN-LAST:event_technologyDeleteActionPerformed

    private void othersUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersUpdateActionPerformed
       
    }//GEN-LAST:event_othersUpdateActionPerformed

    private void othersDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersDeleteActionPerformed
      
    }//GEN-LAST:event_othersDeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTFActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        String str = searchTF.getText();
        
        DefaultTableModel model = (DefaultTableModel) requestsTBL.getModel();
        model.setRowCount(0);
        
        for(Request request : requestDAOImpl.searchRequest(str)){
            model.addRow(new Object[]{
                request.getRequest_id(),
                request.getUser_id(),
                request.getRequested_by(),
                request.getRequest_info(),
                request.getRequest_type(),
                request.getPriority(),
                request.getDate_created()
});
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void typeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeCBActionPerformed
        loadFilteredRequests();
    }//GEN-LAST:event_typeCBActionPerformed

    private void priorityCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityCBActionPerformed
        loadFilteredRequests();
    }//GEN-LAST:event_priorityCBActionPerformed

    private void inProgressTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inProgressTBLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inProgressTBLMouseClicked

    private void recordTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordTBLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_recordTBLMouseClicked

    private void statusCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCBActionPerformed
    JComboBox<String> statusFilterCombo = new JComboBox<>(new String[]{"Completed", "Rejected"});
    statusCB.addActionListener(e -> {
    String selected = (String) statusCB.getSelectedItem();
    loadRequestsByStatus(recordTBL, selected);
});
    }//GEN-LAST:event_statusCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consumableCancelTF;
    private javax.swing.JMenuItem consumableDelete;
    private javax.swing.JTextField consumableNameTF;
    private javax.swing.JPopupMenu consumablePUM;
    private javax.swing.JTextField consumablePreferencesTF;
    private javax.swing.JTextField consumableQuantityTF;
    private javax.swing.JButton consumableSaveBTN;
    private javax.swing.JButton consumableSearchBTN;
    private javax.swing.JTextField consumableSearchTF;
    private javax.swing.JTable consumableTBL;
    private javax.swing.JMenuItem consumableUpdate;
    private javax.swing.JButton equipmentCancelBTN;
    private javax.swing.JMenuItem equipmentDelete;
    private javax.swing.JTextField equipmentNameTF;
    private javax.swing.JPopupMenu equipmentPUM;
    private javax.swing.JTextField equipmentPreferencesTF;
    private javax.swing.JTextField equipmentQuantityTF;
    private javax.swing.JButton equipmentSaveBTN;
    private javax.swing.JButton equipmentSearchBTN;
    private javax.swing.JTextField equipmentSearchTF;
    private javax.swing.JTable equipmentTBL;
    private javax.swing.JMenuItem equipmentUpdate;
    private javax.swing.JTable inProgressTBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton othersCancelBTN;
    private javax.swing.JMenuItem othersDelete;
    private javax.swing.JTextField othersNameTF;
    private javax.swing.JPopupMenu othersPUM;
    private javax.swing.JTextField othersPreferencesTF;
    private javax.swing.JTextField othersQuantityTF;
    private javax.swing.JButton othersSaveBTN;
    private javax.swing.JButton othersSearchBTN;
    private javax.swing.JTextField othersSearchTF;
    private javax.swing.JTable othersTBL;
    private javax.swing.JMenuItem othersUpdate;
    private javax.swing.JComboBox<String> priorityCB;
    private javax.swing.JTable recordTBL;
    private javax.swing.JTable requestsTBL;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField searchTF;
    private javax.swing.JComboBox<String> statusCB;
    private javax.swing.JButton technologyCancelBTN;
    private javax.swing.JMenuItem technologyDelete;
    private javax.swing.JTextField technologyNameTF;
    private javax.swing.JPopupMenu technologyPUM;
    private javax.swing.JTextField technologyPreferencesTF;
    private javax.swing.JTextField technologyQuantityTF;
    private javax.swing.JButton technologySaveBTN;
    private javax.swing.JButton technologySearchBTN;
    private javax.swing.JTextField technologySearchTF;
    private javax.swing.JTable technologyTBL;
    private javax.swing.JMenuItem technologyUpdate;
    private javax.swing.JComboBox<String> typeCB;
    private javax.swing.JMenuItem userMI;
    // End of variables declaration//GEN-END:variables
}
